version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Docker Hub..."
      - echo ${DOCKERHUB_TOKEN} | docker login -u ${DOCKERHUB_USER} --password-stdin 

  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t my-angular-app:latest .

  post_build:
    commands:
      - echo "Tagging and pushing image to Docker Hub..."
      - docker tag my-angular-app:latest ${DOCKERHUB_USER}/my-angular-app:latest
      - docker push ${DOCKERHUB_USER}/my-angular-app:latest

      # ✅ Create the ECS image definition file for CodePipeline deploy stage
      - echo "Creating imagedefinitions.json for ECS deployment..."
      - printf '[{"name":"angular-app","imageUri":"%s"}]' ${DOCKERHUB_USER}/my-angular-app:latest > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
